name: lumi_clips
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies
dependencies:
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  extensions_kit: ^1.1.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  hive_flutter: ^1.1.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf

    - family: semiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf

    - family: courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
